/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/
#include <STM32F303RE.h>
#include <GPIO.h>

uint8_t flag = 0;

int main(void)
{
	//Configure Led pin as output
	__GPIO_EnPCLK(GPIOA);
	__GPIO_init(GPIOA, 5, GPIO_MODE_OUT, GPIO_OTYPE_PP, GPIO_SPEED_LOW, GPIO_NO_PUPD, GPIO_ALT_FNC_0);

	//Configure User Button as Interrupt Generator
	__GPIO_EnPCLK(GPIOC);
	__GPIO_init(GPIOC, 13, GPIO_MODE_IN, GPIO_OTYPE_PP, GPIO_SPEED_LOW, GPIO_NO_PUPD, GPIO_ALT_FNC_0);

	while(1){
		if(__GPIO_readPin(GPIOC, 13) == FALSE)
			__GPIO_writePin(GPIOA, 5, TRUE);
		else
			__GPIO_writePin(GPIOA, 5, FALSE);
	}
}


void EXTI1_IRQHandler(void){
	__GPIO_IRQhandling(0);
}
