/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/
#include <STM32F303RE.h>
#include <GPIO.h>
#include <I2C.h>

/*
 * SCL  --> PB8	(D15)
 * SDA  --> PB9 (D14)
 * SCL debug  --> PB6
 * SDA debug  --> PB7
 * IMPORTANT: arduino Mega PULLUP resistor is already present on SDA and SCL
 * IMPORTANT: arduino Wire Lib. use a 32 byte rx\tx buffer, if more byte are
 * transmitted\received in the same I2C communication it will be discarded
 */

uint8_t SAddr = 0x68;
uint8_t String[] = "Ciao sono STM32F303RE!!";
uint8_t ssize = sizeof(String);

I2C_handle I2C1_handle;

void delay()
{
	uint32_t i;
	for(i=0; i<100; i++);
}


//Button pressed ISR
void EXTI15_10_IRQHandler(void)
{
	//Handle ISR
	__GPIO_IRQhandling(13);

	//Blink LED
	__GPIO_tooglePin(GPIOA, 5);
	delay();
	__GPIO_tooglePin(GPIOA, 5);

	//Enable I2C1
	__I2C_enable(&I2C1_handle);

	//Send String
	__I2C_MasterSend_IT(&I2C1_handle, String, ssize, SAddr, I2C_DISABLE_SR);//Transmit and close communication

}

//I2C1 Event ISR
void I2C1_EV_EXTI23_IRQHandler(void)
{
	//Handle I2C1 ISR
	__I2C_EV_IRQhandle(&I2C1_handle);
}


void initGPIO(void)
{
	//Enable GPIOx peripheral clock
	__GPIO_EnPCLK(GPIOA);
	__GPIO_EnPCLK(GPIOB);
	__GPIO_EnPCLK(GPIOC);

	//Configure User Button as Interrupt Generator
	__GPIO_init(GPIOC, 13, GPIO_MODE_INT_F, GPIO_OTYPE_PP, GPIO_SPEED_LOW, GPIO_NO_PUPD, GPIO_ALT_FNC_0);

	//Configure PA5 as output to drive LED
	__GPIO_init(GPIOA, 5, GPIO_MODE_OUT, GPIO_OTYPE_PP, GPIO_SPEED_LOW, GPIO_NO_PUPD, GPIO_ALT_FNC_0);

	//Configure SCL
	__GPIO_init(GPIOB, 8, GPIO_MODE_AF, GPIO_OTYPE_OD, GPIO_SPEED_HIGH, GPIO_NO_PUPD, GPIO_ALT_FNC_4);

	//Configure SDA
	__GPIO_init(GPIOB, 9, GPIO_MODE_AF, GPIO_OTYPE_OD, GPIO_SPEED_HIGH, GPIO_NO_PUPD, GPIO_ALT_FNC_4);

	//Configure SCL for Logic Analyzer
	__GPIO_init(GPIOB, 6, GPIO_MODE_AF, GPIO_OTYPE_OD, GPIO_SPEED_HIGH, GPIO_NO_PUPD, GPIO_ALT_FNC_4);

	//Configure SDA for Logic Analyzer
	__GPIO_init(GPIOB, 7, GPIO_MODE_AF, GPIO_OTYPE_OD, GPIO_SPEED_HIGH, GPIO_NO_PUPD, GPIO_ALT_FNC_4);
}


void initI2C1(void)
{
	//configure I2C1
	I2C1_handle.pI2Cx = I2C1;
	I2C1_handle.pI2Cx_conf.Speed = 100000; //100kHz
	I2C1_handle.pI2Cx_conf.Addr  = 0x0;
	I2C1_handle.pTxBuf = NULL;
	I2C1_handle.pRxBuf = NULL;
	I2C1_handle.TxLen  = 0;
	I2C1_handle.RxLen  = 0;

	//Initialize I2C1
	__I2C_EnPCLK(I2C1);
	__I2C_init(&I2C1_handle);
}

void __I2C_AppEventCallback(I2C_handle *pI2Cx_h, uint8_t AppEv)
{
	if(AppEv == I2C_EVENT_STOPF)
	{
		//Disable I2C1
		__I2C_disable(&I2C1_handle);
	}
}

void setup()
{
	//Initialize I2C1
	initI2C1();

	//Initialize GPIO pins
	initGPIO();

	//initialize IRQ for I2C and GPIO
	__I2C_IRQconfig(&I2C1_handle, EN, 1);
	__GPIO_IRQconfig(13, EN, 0);
}

int main(void)
{
	//Setup GPIO and I2C1
	setup();

	while(1)
	{
		//do stuff here
	}

}
