/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/
#include <STM32F303RE.h>
#include <math.h>

int main(void)
{
	//Set SYSCLK to 72MHz
	__RCC_setSYSCLK(SYSCLK_72MHZ);

	//Enable GPIO peripheral clock
	__GPIO_EnPCLK(GPIOA);
	__GPIO_EnPCLK(GPIOB);

	//initialize WS pin
	__GPIO_init(GPIOA, 4, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_SPEED_HIGH, GPIO_NO_PUPD, GPIO_ALT_FNC_6);

	//initialize CLK pin
	__GPIO_init(GPIOB, 3, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_SPEED_HIGH, GPIO_NO_PUPD, GPIO_ALT_FNC_6);

	//initialize SD pin
	__GPIO_init(GPIOB, 5, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_SPEED_HIGH, GPIO_NO_PUPD, GPIO_ALT_FNC_6);

	//initialize MCLK pin
	//__GPIO_init(GPIOA, 8, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_SPEED_HIGH, GPIO_NO_PUPD, GPIO_ALT_FNC_5);

	I2S_Handle I2S_handle;

	I2S_handle.pI2Sx = I2S3;
	I2S_handle.pI2Sx_conf.Mode = I2S_MODE_MASTER_TX;
	I2S_handle.pI2Sx_conf.Fs   = I2S_FS_44KHZ;
	I2S_handle.pI2Sx_conf.Std  = I2S_STD_PHILIP;
	I2S_handle.pI2Sx_conf.DataSize = I2S_DS_16BIT;
	I2S_handle.pI2Sx_conf.ChLen = I2S_CHLEN_16BIT;
	I2S_handle.pI2Sx_conf.Cpol = I2S_CPOL_LOW;
	I2S_handle.pI2Sx_conf.MCLK = I2S_MCLK_DIS;
	I2S_handle.pI2Sx_conf.Odd  = I2S_ODD_LOW;

	//initialize I2S2
	__I2S_init(&I2S_handle);

	//enable I2S2 peripheral
	__I2S_enable(&I2S_handle);

	uint32_t sc = __RCC_getSYSCLK();

	uint16_t val = 0;

	while(1)
	{
		__I2S_sendData(&I2S_handle, val, val);
		val++;
	}
}
