/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/
#include <STM32F303RE.h>
#include <math.h>

#define TABLESIZE	256
#define BUFSIZE		256
#define I2S_BUFSIZE	(2*BUFSIZE)
#define PI 			3.1415926535

I2S_Handle I2S_handle;
int16_t SinTable[256] = {0};
int16_t i2s_TxBuf[I2S_BUFSIZE] = {0};
int16_t AudioBuf[BUFSIZE] = {0};
uint8_t Tidx = 0;
uint8_t refill = 0;

void fillSinTable(void)
{
	uint16_t i;
	double k = 2*PI/TABLESIZE;
	for(i=0; i<TABLESIZE; i++)
	{
		SinTable[i] = (int16_t)(32767.0*sin(k*(double)i));
	}
}

void fillAudioBuf(void)
{
	uint16_t i;
	for(i=0; i<BUFSIZE; i++)
	{
		AudioBuf[i] = SinTable[Tidx++];

		if(Tidx == TABLESIZE)
			Tidx = 0;
	}
}

void fillTxBuf(void)
{
	uint16_t i;
	for(i=0; i<I2S_BUFSIZE/2; i++)
	{
		i2s_TxBuf[i*2]     = AudioBuf[i];//Left
		i2s_TxBuf[i*2 + 1] = AudioBuf[i];//Right
	}
}

void SPI3_IRQHandler(void)
{
	//handle interrupt request
	__I2S_IRQhandle(&I2S_handle);
}

int main(void)
{
	//initialize Sine Table
	fillSinTable();

	//Set System Clock to 72MHz
	__RCC_setSYSCLK(SYSCLK_72MHZ);

	//Enable Peripheral Clock
	__GPIO_EnPCLK(GPIOA);
	__GPIO_EnPCLK(GPIOB);

	//initialize WS pin
	__GPIO_init(GPIOA, 4, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_SPEED_HIGH, GPIO_NO_PUPD, GPIO_ALT_FNC_6);

	//initialize CLK pin
	__GPIO_init(GPIOB, 3, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_SPEED_HIGH, GPIO_NO_PUPD, GPIO_ALT_FNC_6);

	//initialize SD pin
	__GPIO_init(GPIOB, 5, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_SPEED_HIGH, GPIO_NO_PUPD, GPIO_ALT_FNC_6);

	//initialize MCLK pin
	//__GPIO_init(GPIOA, 8, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_SPEED_HIGH, GPIO_NO_PUPD, GPIO_ALT_FNC_5);


	I2S_handle.pI2Sx = I2S3;
	I2S_handle.pI2Sx_conf.Mode = I2S_MODE_MASTER_TX;
	I2S_handle.pI2Sx_conf.Fs   = I2S_FS_44KHZ;
	I2S_handle.pI2Sx_conf.Std  = I2S_STD_PHILIP;
	I2S_handle.pI2Sx_conf.DataSize = I2S_DS_16BIT;
	I2S_handle.pI2Sx_conf.ChLen = I2S_CHLEN_16BIT;
	I2S_handle.pI2Sx_conf.Cpol = I2S_CPOL_LOW;
	I2S_handle.pI2Sx_conf.MCLK = I2S_MCLK_DIS;
	I2S_handle.pI2Sx_conf.Odd  = I2S_ODD_LOW;

	//initialize I2S3
	__I2S_init(&I2S_handle);

	//Enable I2S3 interrupt requst (SPI3)
	__I2S_IRQconfig(&I2S_handle, EN, 0);

	//enable I2S3 peripheral
	__I2S_enable(&I2S_handle);

	//send first buffer full of zeros
	__I2S_sendData_IT(&I2S_handle, (uint16_t *)i2s_TxBuf, I2S_BUFSIZE);
	refill = 0;

	while(1)
	{
		//timer used to measure CPU free time
		uint32_t timer = 0;

		//do audio engine here
		fillAudioBuf();

		//wait until new audio packet is request
		while(!refill) timer++;

		//fill again TX buffer
		fillTxBuf();
		refill = 0;
	}
}

void __I2S_AppEventCallback(I2S_Handle *pI2Sx_h,	/*I2Sx handle address	*/
							uint8_t     AppEv)		/*@I2S_EVENT			*/
{
	if(AppEv == I2S_EVENT_TX_COMPLETE)
	{
		__I2S_sendData_IT(pI2Sx_h, (uint16_t *)i2s_TxBuf, I2S_BUFSIZE);
		//request new packet
		refill = 1;
	}
}
