/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/
#include "STM32F303RE.h"

uint8_t flag = 0;

int main(void)
{
	printf("flag = %d\n", flag);
	for(;;);
}

void SystemInit(void){
	flag = 1;
}
